import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gilroy = localFont({
  src: [
    {path: "../../public/fonts/gilroy-regular.woff2"}
  ],
  variable: "--font-gilroy",
  display: "swap"
})
const chronicle = localFont({
  src: [
    {path: "../../public/fonts/chronicle-display.woff2"}
  ],
  variable: "--font-chronicle",
  display: "swap"
})

export const metadata: Metadata = {
  title: "MNTN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroy.variable} ${chronicle.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
